#!/usr/bin/env bash
# Creates the Forge pipeline directory structure in the target directory.
# Idempotent: safe to run multiple times. Never overwrites existing files.
#
# Usage:
#   scripts/init-pipeline.sh [ROOT]
#   scripts/init-pipeline.sh [ROOT] --dry-run         # show plan, don't create
#   scripts/init-pipeline.sh [ROOT] --manifest-only   # JSON manifest, no chatter
#   scripts/init-pipeline.sh --help
#
# ROOT defaults to the current working directory.
#
# Exit codes:
#   0  success (or dry-run completed)
#   2  invalid flag
#
# Ref: T-002 (original), T-103 (dry-run + manifest)

set -euo pipefail

DRY_RUN=0
MANIFEST_ONLY=0
ROOT="."

for arg in "$@"; do
    case "$arg" in
        --dry-run)
            DRY_RUN=1
            ;;
        --manifest-only)
            MANIFEST_ONLY=1
            ;;
        --help|-h)
            cat <<EOF
Forge pipeline initializer

Usage:
  $(basename "$0") [ROOT] [--dry-run] [--manifest-only]

Options:
  ROOT             Target directory (default: current working directory)
  --dry-run        Show what would be created without writing files
  --manifest-only  Emit a JSON manifest to stdout; suppress all other output
  --help, -h       Show this help

The script is idempotent: existing files are never overwritten.
EOF
            exit 0
            ;;
        --*)
            echo "unknown flag: $arg" >&2
            echo "run with --help for usage" >&2
            exit 2
            ;;
        *)
            ROOT="$arg"
            ;;
    esac
done

CREATED=()
SKIPPED=()

# Print to stdout unless --manifest-only is set.
say() {
    if [ "$MANIFEST_ONLY" = "0" ]; then
        echo "$@"
    fi
}

# Track and (unless dry-run) create a .gitkeep'd directory.
create_gitkeep() {
    local rel="$1"
    local dir="$ROOT/$rel"
    if [ -d "$dir" ] && [ -f "$dir/.gitkeep" ]; then
        SKIPPED+=("$rel/.gitkeep")
        return
    fi
    if [ "$DRY_RUN" = "1" ]; then
        say "would create: $rel/.gitkeep"
        CREATED+=("$rel/.gitkeep")
        return
    fi
    mkdir -p "$dir"
    touch "$dir/.gitkeep"
    say "created: $rel/.gitkeep"
    CREATED+=("$rel/.gitkeep")
}

# Track and (unless dry-run) create a file with the given content.
create_file() {
    local rel="$1"
    local content="$2"
    local path="$ROOT/$rel"
    if [ -f "$path" ]; then
        SKIPPED+=("$rel")
        return
    fi
    if [ "$DRY_RUN" = "1" ]; then
        say "would create: $rel"
        CREATED+=("$rel")
        return
    fi
    mkdir -p "$(dirname "$path")"
    printf '%s' "$content" > "$path"
    say "created: $rel"
    CREATED+=("$rel")
}

# Track and (unless dry-run) ensure an empty file exists.
create_empty() {
    local rel="$1"
    local path="$ROOT/$rel"
    if [ -f "$path" ]; then
        SKIPPED+=("$rel")
        return
    fi
    if [ "$DRY_RUN" = "1" ]; then
        say "would create: $rel"
        CREATED+=("$rel")
        return
    fi
    mkdir -p "$(dirname "$path")"
    touch "$path"
    say "created: $rel"
    CREATED+=("$rel")
}

# ---------- pipeline/ stage directories ----------

create_gitkeep "pipeline/01-srs"
create_gitkeep "pipeline/02-product-ux/wireframes"
create_gitkeep "pipeline/03-architecture/adr"
create_gitkeep "pipeline/04-spec"
create_gitkeep "pipeline/05-plan"
create_gitkeep "pipeline/06-implementation"
create_gitkeep "pipeline/07-evaluation"
create_gitkeep "pipeline/08-deploy"
create_gitkeep "pipeline/09-monitor"
create_gitkeep "pipeline/10-feedback"
create_gitkeep "pipeline/11-resolve"
create_gitkeep "pipeline/12-release"

# ---------- pipeline/state.md ----------

NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
STATE_CONTENT="---
schema_version: 1
project_type: unknown
cycle: 1
current_stage: 0
current_task: null
current_milestone: null
total_tasks: null
last_updated: ${NOW}
blockers: []
---
# Pipeline State

## Stage History

| Stage | Started | Completed | Gate | Notes |
|-------|---------|-----------|------|-------|

## Last Reflection

*(No reflections yet — generated by the reflector agent on each session stop)*
"
create_file "pipeline/state.md" "$STATE_CONTENT"

# ---------- tasks/ ----------

TODO_CONTENT='# tasks/todo.md

> Active work tracker. The current task lives at the top. Completed tasks archive below.

---

## Active Task

*(Run `/forge:srs` to begin Stage 1 — Requirements)*
'
create_file "tasks/todo.md" "$TODO_CONTENT"

LESSONS_CONTENT='# Lessons Learned

> Append-only log of corrections and the rules that prevent them.
> Read at session start.

## Lessons

*(None yet)*
'
create_file "tasks/lessons.md" "$LESSONS_CONTENT"

# ---------- .forge/ ----------

LESSONS_YAML='schema_version: 1
lessons: []
'
create_file ".forge/lessons.yaml" "$LESSONS_YAML"
create_empty ".forge/patterns.jsonl"

# Create .forge/sessions/ as a tracked dir
create_gitkeep ".forge/sessions"

# ---------- output ----------

if [ "$MANIFEST_ONLY" = "1" ]; then
    # JSON manifest. Hand-rolled to avoid jq dependency.
    printf '{"dry_run":%s,"root":"%s","created":[' \
        "$([ "$DRY_RUN" = "1" ] && echo true || echo false)" \
        "$(realpath "$ROOT" 2>/dev/null || echo "$ROOT")"
    first=1
    for c in "${CREATED[@]:-}"; do
        [ -z "$c" ] && continue
        [ $first = 0 ] && printf ','
        printf '"%s"' "$c"
        first=0
    done
    printf '],"skipped":['
    first=1
    for s in "${SKIPPED[@]:-}"; do
        [ -z "$s" ] && continue
        [ $first = 0 ] && printf ','
        printf '"%s"' "$s"
        first=0
    done
    printf ']}\n'
    exit 0
fi

echo ""
if [ "$DRY_RUN" = "1" ]; then
    echo "─────────────────────────────────────────────────────────────"
    echo "Forge pipeline plan:"
    echo "  ${#CREATED[@]} file(s) would be created"
    if [ "${#SKIPPED[@]}" -gt 0 ]; then
        echo "  ${#SKIPPED[@]} skipped (already present, will not be overwritten)"
    fi
    echo "  target: $(realpath "$ROOT" 2>/dev/null || echo "$ROOT")"
    echo ""
    echo "Re-run without --dry-run to apply."
else
    echo "─────────────────────────────────────────────────────────────"
    echo "Forge pipeline initialized in: $(realpath "$ROOT" 2>/dev/null || echo "$ROOT")"
    echo "  ${#CREATED[@]} file(s) created"
    if [ "${#SKIPPED[@]}" -gt 0 ]; then
        echo "  ${#SKIPPED[@]} already existed (not overwritten)"
    fi
fi