#!/usr/bin/env bash
# Creates the Forge pipeline directory structure in the current working directory.
# Idempotent: safe to run multiple times. Never overwrites existing files.
set -euo pipefail

ROOT="${1:-.}"

create_gitkeep() {
    local dir="$ROOT/$1"
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
        touch "$dir/.gitkeep"
        echo "created: $1/.gitkeep"
    fi
}

create_file() {
    local path="$ROOT/$1"
    shift
    local content="$*"
    if [ ! -f "$path" ]; then
        mkdir -p "$(dirname "$path")"
        printf '%s' "$content" > "$path"
        echo "created: $1"
    fi
}

# pipeline/ stage directories
create_gitkeep "pipeline/01-srs"
create_gitkeep "pipeline/02-product-ux/wireframes"
create_gitkeep "pipeline/03-architecture/adr"
create_gitkeep "pipeline/04-spec"
create_gitkeep "pipeline/05-plan"
create_gitkeep "pipeline/06-implementation"
create_gitkeep "pipeline/07-evaluation"
create_gitkeep "pipeline/08-deploy"
create_gitkeep "pipeline/09-monitor"
create_gitkeep "pipeline/10-feedback"
create_gitkeep "pipeline/11-resolve"
create_gitkeep "pipeline/12-release"

# pipeline/state.md — initial state, not overwritten if it exists
STATE="$ROOT/pipeline/state.md"
if [ ! -f "$STATE" ]; then
    NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    cat > "$STATE" <<HEREDOC
---
schema_version: 1
project_type: unknown
cycle: 1
current_stage: 0
current_task: null
current_milestone: null
total_tasks: null
last_updated: ${NOW}
blockers: []
---

# Pipeline State

## Stage History
| Stage | Started | Completed | Gate | Notes |
|-------|---------|-----------|------|-------|

## Last Reflection
*(No reflections yet — generated by the reflector agent on each session stop)*
HEREDOC
    echo "created: pipeline/state.md"
fi

# tasks/
TASKS_TODO="$ROOT/tasks/todo.md"
if [ ! -f "$TASKS_TODO" ]; then
    mkdir -p "$ROOT/tasks"
    cat > "$TASKS_TODO" <<'HEREDOC'
# tasks/todo.md

> Active work tracker. The current task lives at the top. Completed tasks archive below.

---

## Active Task

*(Run `/forge:srs` to begin Stage 1 — Requirements)*
HEREDOC
    echo "created: tasks/todo.md"
fi

TASKS_LESSONS="$ROOT/tasks/lessons.md"
if [ ! -f "$TASKS_LESSONS" ]; then
    mkdir -p "$ROOT/tasks"
    cat > "$TASKS_LESSONS" <<'HEREDOC'
# Lessons Learned

> Append-only log of corrections and the rules that prevent them.
> Read at session start.

## Lessons

*(None yet)*
HEREDOC
    echo "created: tasks/lessons.md"
fi

# .forge/
FORGE_DIR="$ROOT/.forge"
mkdir -p "$FORGE_DIR/sessions"

LESSONS_YAML="$FORGE_DIR/lessons.yaml"
if [ ! -f "$LESSONS_YAML" ]; then
    cat > "$LESSONS_YAML" <<'HEREDOC'
schema_version: 1
lessons: []
HEREDOC
    echo "created: .forge/lessons.yaml"
fi

PATTERNS_JSONL="$FORGE_DIR/patterns.jsonl"
if [ ! -f "$PATTERNS_JSONL" ]; then
    touch "$PATTERNS_JSONL"
    echo "created: .forge/patterns.jsonl"
fi

echo ""
echo "Forge pipeline initialized in: $(realpath "$ROOT")"
